---
abstract: 'interface to read and parse BibTeX files'
author:
  - 'Alberto Simões <ambs@cpan.org>'
  - 'Greg Ward <gward@python.net>'
build_requires:
  Capture::Tiny: 0.06
  Config::AutoConf: 0.16
  ExtUtils::CBuilder: 0.27
  ExtUtils::LibBuilder: 0.02
  File::Copy: 0
  Module::Build: 0.3603
configure_requires:
  Config::AutoConf: 0.16
  ExtUtils::LibBuilder: 0.02
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3622'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-BibTeX
provides:
  Text::BibTeX:
    file: lib/Text/BibTeX.pm
    version: 0.49
  Text::BibTeX::BibEntry:
    file: lib/Text/BibTeX/Bib.pm
  Text::BibTeX::BibFormat:
    file: lib/Text/BibTeX/BibFormat.pm
  Text::BibTeX::BibSort:
    file: lib/Text/BibTeX/BibSort.pm
  Text::BibTeX::BibStructure:
    file: lib/Text/BibTeX/Bib.pm
  Text::BibTeX::Entry:
    file: lib/Text/BibTeX/Entry.pm
  Text::BibTeX::File:
    file: lib/Text/BibTeX/File.pm
  Text::BibTeX::Name:
    file: lib/Text/BibTeX/Name.pm
  Text::BibTeX::NameFormat:
    file: lib/Text/BibTeX/NameFormat.pm
  Text::BibTeX::SimpleValue:
    file: lib/Text/BibTeX/Value.pm
  Text::BibTeX::Structure:
    file: lib/Text/BibTeX/Structure.pm
  Text::BibTeX::StructuredEntry:
    file: lib/Text/BibTeX/Structure.pm
  Text::BibTeX::Value:
    file: lib/Text/BibTeX/Value.pm
resources:
  license: http://dev.perl.org/licenses/
version: 0.49
